<a href="https://colab.research.google.com/github/anmuhina/VkCloud/blob/master/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#1. Создать вектор (одномерный массив) размера 10, заполненный нулями
zero_vec = np.zeros(10)
print(zero_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#2. Создать вектор (одномерный массив) размера 10, заполненный нулями, пятый элемент должен быть равен 1
vec = np.zeros([10])
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
#3. Создать вектор (одномерный массив) размера 20. Заполнить его случайными значениями. Найти индексы ненулевых элементов
vec = np.random.random([20])
np.nonzero(vec)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

In [7]:
#4. Создать массив 3x3x3. Заполнить его случайными значениями
vec = np.random.random((3, 3, 3))
vec

array([[[0.37888941, 0.10718612, 0.1034488 ],
        [0.90807636, 0.88288344, 0.67607171],
        [0.77344077, 0.19916614, 0.74927362]],

       [[0.12146444, 0.13390853, 0.07001497],
        [0.2207283 , 0.04670087, 0.05929597],
        [0.32725305, 0.17154771, 0.62501301]],

       [[0.10298448, 0.822198  , 0.9308097 ],
        [0.54217141, 0.27759691, 0.86675613],
        [0.88991335, 0.44014712, 0.42562251]]])

In [12]:
#5. Создать вектор (одномерный массив) размера 10. Заполнить его случайными значениями. Найти среднее значение всех элементов
vec = np.random.randint(0,20,10)
print(vec)
vec.mean()

[19 16 15 15  2  3  5 11 18 19]


12.3

In [19]:
#6. Создать две матрицы 5x3 и 3x2. Найти их произведение
matrix1 = np.array([[1,2,3],[2,3,4],[4,5,6],[6,7,8],[8,9,10]])
matrix2 = np.array([[0,1],[2,3],[4,5]])
np.dot(matrix1, matrix2)

array([[16, 22],
       [22, 31],
       [34, 49],
       [46, 67],
       [58, 85]])

In [22]:
#7. Создать две матрицы 4x4 и 4x4. Найти их произведение. Найти диагональные элементы произведения матриц
matrix1 = np.random.random((4,4))
matrix2 = np.random.random((4,4))
mult = matrix1 * matrix2
print(mult)
mult.diagonal()

[[0.05046125 0.65877105 0.24352009 0.523788  ]
 [0.83754903 0.12128477 0.23332318 0.62446392]
 [0.11460762 0.44535936 0.79020866 0.22377413]
 [0.24918805 0.12771298 0.5612978  0.33089972]]


array([0.05046125, 0.12128477, 0.79020866, 0.33089972])

In [23]:
#8. Создать вектор (одномерный массив) размера 20. Заполнить его случайными значениями. Заменить максимальный элемент на ноль
vec = np.random.randint((1,20,20))
print(vec)
vec[vec.argmax()] = 0
vec

[ 0  3 14]


array([0, 3, 0])

In [26]:
#9. Создать вектор (одномерный массив) размера 20. Заполнить его случайными значениями. Напечатать все значения в массиве без повторений
vec = np.random.randint((1,20,20))
print(vec)
np.unique(vec)

[ 0 18 13]


array([ 0, 13, 18])

In [27]:
#10. Создать матрицу. Отнять среднее из каждой строки в матрице
matrix = np.random.randint(1, 100, [3,3])
print(matrix.mean(axis=1))
matrix = matrix - matrix.mean(axis=1, keepdims=True)
matrix

[18.33333333 67.66666667 49.33333333]


array([[ -5.33333333,  -6.33333333,  11.66666667],
       [-30.66666667,  20.33333333,  10.33333333],
       [-27.33333333,  40.66666667, -13.33333333]])

In [30]:
#11. Создать матрицу. Поменять две строки в матрице
matrix = np.random.randint(1, 100, [3,3])
print(matrix)
matrix[[0,2]] = matrix[[2,0]]
matrix

[[84 41 32]
 [86 21 94]
 [36 70 18]]


array([[36, 70, 18],
       [86, 21, 94],
       [84, 41, 32]])